### ISSUE TITLE
Tab2: Plots will not be displayed until the window is resized.

### ISSUE THREAD

**Issue by vnagaraju14** [lfiondella/SRT#28]

**Comment by arhik** [comment]
window resize event is helping the redraw of plot. That should not be the case. The reactivity of plot redraw is missing. This should be a minor fix. I am assigning Allen for this. @a1729nikora Did  you have any lead to solve this? This is just to let others know that this issue is taken care of by you. We know you are working on this.

**Comment by a1729nikora** [comment]
I've taken care of this one over the weekend.  I was down with a cold today, so haven't looked at my e-mail before now.  I've also taken care of a few other things that I'll let you know about tomorrow.

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by vnagaraju14** [comment]
Thank you for the update Allen. Hope you feel better. 

-Vidhya 

----- Original Message -----

**Comment by arhik** [comment]
This is fixed in https://github.com/lfiondella/SRT/commit/11eece12edaed0eb4b47c04fc969569b044abb87

I think i can close this. We can reraise this if there are any inconsistency.
